### ISSUE TITLE
time-consuming cyclone

### ISSUE THREAD

**Issue by csandorfr** [MarioniLab/archive-scran#3]
Hi,

I'm trying to run cyclone with the small example given in the documentation of cyclone (assignments <- cyclone(test, out,verbose=TRUE)) and it seems very long (no results after one hour). I was wondering if this function was time-consuming.

Number of G1 pairs: 87
Number of S pairs: 93
Number of G2M pairs: 94

dim(test) 20 50

Cynthia

**Comment by LTLA** [comment]
If you're running on a Mac, this is probably due to something funny happening with the _multicore_ machinery. Try setting `BPPARAM=SerialParam()` to coerce single-core execution, and see if that makes it run faster. The latest version of _scran_ will have this by default to avoid such problems in the future. 

Also, for future reference, this kind of question should be posted to the Bioconductor support site (https://support.bioconductor.org) where it'll be more helpful to others with similar problems.

**Comment by csandorfr** [comment]
Many thanks for two advices. It solve my pb.
